spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
    alicloud:
      access-key: LTAI4G6nRjPNrpTUyYJhjK4Q
      secret-key: CGhdrl1x51bn4Wsmt6YYRYGE4pvLAT
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: dismall-yang
  zipkin:
    base-url: 10.43.1.52:9411/
    # 关闭我们自动的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
server:
  port: 30000
